[package]
name = "stremio-official-addons"
description = "All of the stremio official addons"
version = "2.0.11"
authors = ["Smart Code OOD"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Stremio/stremio-official-addons"
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/addons.json",
    "/README.md"
]

[features]

default = ["json", "std"]
std = ["serde_json/std", "once_cell/std"]

json = ["serde_json", "once_cell"]

[dependencies]

serde_json = { version = "1", optional = true, default-features = false }
once_cell = { version = "1", optional = true, default-features = false }
