name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20.10
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
    - name: Rust setup (1.61)
      uses: dtolnay/rust-toolchain@1.61
    - name: Install NPM dependencies
      run: npm ci
    - name: Build v1 and generate v1 index.json
      run: npm run --workspace stremio-official-addons build
    - name: Build v2
      run: npm run --workspace official-addons-v2 build
