name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
    - name: Set default rust toolchain
      run: rustup default 1.61.0
    - name: Install NPM dependencies
      run: npm ci
    - name: Build
      run: npm run build
