name: Publish

on:
  release:
    types: [published]

env:
  RUST_VERSION: stable
  NODE_VERSION: 12

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        registry-url: https://registry.npmjs.org/

    - name: Set default Rust version - ${{ env.RUST_VERSION }}
      run: rustup default ${{ env.RUST_VERSION }}

    - name: Install NPM dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

    - name: Publish to crates.io
      run: cargo publish --allow-dirty --token "$CARGO_AUTH_TOKEN"
      env:
        CARGO_AUTH_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_TOKEN }}
