name: Publish

on:
  release:
    types: [published]
    
jobs:
  # FIXME: needs a running server locally for the local-addon
  # publish-v1:
  #   if: ${{ startsWith(github.event.release.tag_name, 'v1') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Setup NodeJS
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 20
  #       cache: 'npm'
  #       registry-url: https://registry.npmjs.org/
  #   - name: Install NPM dependencies
  #     run: npm ci
  #   - name: Publish to NPM
  #     run: npm publish --workspace stremio-official-addons --access public
  #     env:
  #       NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish-v2:
    if: ${{ startsWith(github.event.release.tag_name, 'v2') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        registry-url: https://registry.npmjs.org/
    - name: Rust setup (1.61)
      uses: dtolnay/rust-toolchain@1.61
    - name: Install NPM dependencies
      run: npm ci
    - name: Build
      run: npm run --workspace official-addons-v2 build
    - name: Publish to NPM
      run: npm publish --workspace official-addons-v2 --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    - name: Publish to crates.io
      run: cargo publish -p stremio-official-addons --allow-dirty --token "$CARGO_AUTH_TOKEN"
      env:
        CARGO_AUTH_TOKEN: ${{ secrets.CRATES_IO_PUBLISH_TOKEN }}
